### ISSUE TITLE
Switching between light and dark mode

### ISSUE THREAD

**Issue by pbar1** [rarylson/anyconnect-macosx-menubar#1]
The icon looks great! Thanks for compiling this together. Right now, when switching to dark mode while using the light mode icons (for example, and vice versa), the icons themselves don't switch and would require manual steps to switch. How can this be accomplished?

**Comment by rarylson** [comment]
Hi pbar1@,

It seems that there is a way of automatically switching the icons from dark mode to light mode and vice-versa, following the configuration of the operating system.

To make this work, it's necessary to create **template images**, which are images without color information.

According to the Apple docs: https://developer.apple.com/design/human-interface-guidelines/macos/extensions/menu-bar-extras/

> Use a template image to represent your menu bar extra. A template image discards color information and uses a mask to produce the appearance you see onscreen. Template images automatically adapt to the user’s appearance settings, so they look good on both dark and light menu bars, and when your menu bar extra is selected.

However, I'm not expert on Photoshop or similar softwares (I created most icons using draw.io instead - which doesn't create template images).

So, to be able to make it work (automatically switching the icons from dark mode to light mode and vice-versa), someone must recreate the icons using the right tools in the right format.

But please note that the way `anyconnect-macosx-menubar` changes the icons today is via a hack (setting custom icons is not supported by Cisco). So, I don't know if only replacing the PNG icons with template images would work here. This should be tested.

**Comment by pbar1** [comment]
I see, thanks for that info. I _believe_ the following command (using ImageMagick) should be sufficient to [convert the images to their alpha channel masks](https://legacy.imagemagick.org/Usage/masking/) for use as template images. I tried it on both the dark and light versions of the images from this repo and got identical results, though I too am by no means a photo guru.

```sh
convert example.png -alpha extract -alpha on -alpha copy exampleTemplate.png
```

If you've got [`fd`](https://github.com/sharkdp/fd) or a similar tool, that can be done from the root of the unzipped Resources directory in batch:

```sh
fd --extension png --exec convert {/.}.png -alpha extract -alpha on -alpha copy {/.}Template.png
```

Now, all this being said, I've yet to check it it'll just work by replacing AnyConnect's resources with these. [According to this StackOverflow post](https://stackoverflow.com/questions/38039262/creating-a-template-image-dynamically-for-osx-menu-bar), under the hood, either the `template` property for the `NSImage` needs to be set to true, or the image needs to have the suffix `Template.png` for example. My guess is that we're gonna be out of luck here as I doubt AnyConnect's code has this set to true, or somehow respects the filename suffix. But I'll test it out and report back.

Update: Yeah I tried and it doesn't work. Also tried using `bbe` to edit the binary's filename strings to take in their `Template` suffixed versions; that resulted in the binary not starting up, likely due to code signing, so I won't go down that rabbit hole. Cisco should just make these default!

**Comment by rarylson** [comment]
Thanks for the tests.

So, I guess the only solution here would be to have Cisco updating their own app code and the "menu bar extra" images.

Just a curiosity, sharing a doc with has more info about template images: https://developer.apple.com/design/human-interface-guidelines/macos/icons-and-images/custom-icons/
